name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Check for Bad Smells
      run: cargo clippy -- -Dwarnings
    - name: Check Code Format
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test --verbose
